### ISSUE TITLE
Support for log scale in optimization parameters

### ISSUE THREAD

**Issue by RikiTikkiTavi** [NormanTUD/OmniOpt#14]
**Is your feature request related to a problem? Please describe.**
Sample parameter values from the log domain.

**Describe the solution you'd like**
See "log_scale" parameter:
https://ax.dev/api/core.html#ax.core.parameter.RangeParameter
See "log" parameter:
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.suggest_float

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by NormanTUD** [comment]
Please check if fixed in ace21b0
